# -*- coding: utf-8 -*-
"""document_processor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZ3pdbkpHVgXm8Ir9d-syuxNKND5RQAk
"""

from typing import List, Optional

class Document:
    def __init__(self, Url: str, PubDate: int, FetchTime: int, Text: Optional[str] = None, FirstFetchTime: Optional[int] = None):
        self.Url = Url
        self.PubDate = PubDate
        self.FetchTime = FetchTime
        self.Text = Text
        self.FirstFetchTime = FirstFetchTime

    def __repr__(self):
        return f"Document(Url={self.Url}, PubDate={self.PubDate}, FetchTime={self.FetchTime}, Text={self.Text}, FirstFetchTime={self.FirstFetchTime})"


class Processor:
    def Process(self, documents: List[Document]) -> Optional[Document]:
        if not documents:
            return None

        # Инициализируем результат с значениями первого документа
        result_doc = documents[0]
        result_doc.Text = documents[0].Text
        result_doc.FetchTime = documents[0].FetchTime
        result_doc.PubDate = documents[0].PubDate
        result_doc.FirstFetchTime = documents[0].FetchTime

        for doc in documents:
            # Обновляем Text и FetchTime с значениями документа с наибольшим FetchTime
            if doc.FetchTime > result_doc.FetchTime:
                result_doc.Text = doc.Text
                result_doc.FetchTime = doc.FetchTime

            # Обновляем PubDate с значением документа с наименьшим FetchTime
            if doc.FetchTime < result_doc.PubDate:
                result_doc.PubDate = doc.FetchTime

            # Обновляем FirstFetchTime с наименьшим FetchTime
            if doc.FetchTime < result_doc.FirstFetchTime:
                result_doc.FirstFetchTime = doc.FetchTime

        return result_doc


if __name__ == "__main__":
    # Пример использования
    documents = [
        Document(Url="1", PubDate=2, FetchTime=3, Text="Initial Text 1"),
        Document(Url="1", PubDate=2, FetchTime=5, Text="Updated Text"),
        Document(Url="1", PubDate=2, FetchTime=1, Text="Old Text")
    ]

    processor = Processor()
    result = processor.Process(documents)
    print(result)